draft_lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
from lab_1.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^$', index)
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_8/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^$', RedirectView.as_view(url='lab-9/', permanent=True), name=''),
]

lab_8/models.py
from django.db import models

# Create your models here.

lab_8/views.py
from django.shortcuts import render

# Create your views here.
name = 'Fannyah'

def index(request):
    response = {'author' : name}
    html = "lab_8/lab_8.html"
    return render(request, html, response)

lab_8/templates/lab_8/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p class="footer">&copy; Made with tears by Fannyah</p>

lab_8/templates/lab_8/partials/header.html
<!-- templates/lab_8/partials/header.html -->
<nav class="navbar navbar-default" style="background-color: pink">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'lab-8:index' %}" style="color: black; font-size: 24px; text-align: center;">WELCOME TO MY LAB 8🎉</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">See All labs<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'lab-1:index' %}">Lab 1</a></li>
            <li><a href="{% url 'lab-2:index' %}">Lab 2</a></li>
            <li><a href="{% url 'lab-3:index' %}">Lab 3</a></li>
            <li><a href="{% url 'lab-4:index' %}">Lab 4</a></li>
            <li><a href="{% url 'lab-5:index' %}">Lab 5</a></li>
            <li><a href="{% url 'lab-6:index' %}">Lab 6</a></li>
            <li><a href="{% url 'lab-7:index' %}">Lab 7</a></li>
            <li><a href="{% url 'lab-8:index' %}">Lab 8</a></li>
            <li><a href="{% url 'lab-9:index' %}">Lab 9</a></li>
            <li><a href="{% url 'lab-10:index' %}">Lab 10</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>